from django.conf.urls import patterns, url

from ourapp import views

urlpatterns = patterns('',
url(r'^dish/(?P<dishID>\d+)/$', views.dish, name='dish'),
url(r'^restaurant/(?P<restaurantID>\d+)/$', views.restaurant, name='restaurant'),
url(r'^customer/(?P<customerID>\d+)/$', views.customer, name='customer'),
url(r'^index/$', views.index, name='index'),
url(r'^restaurants/(json)?$', views.restaurant_list),
url(r'^restaurants/([0-9]+)/(json)?$', views.restaurant_detail),
url(r'^restaurants/([0-9]+)/dishes/(json)?$', views.restaurant_dishes),
url(r'^restaurants/([0-9]+)/reviews/(json)?$', views.restaurant_reviews),
url(r'^customers/(json)?$', views.customer_list),
url(r'^customers/([0-9]+)/(json)?$', views.customer_detail),
url(r'^customers/([0-9]+)/restaurantreviews/(json)?$', views.customer_restaurant_reviews),
url(r'^customers/([0-9]+)/dishreviews/(json)?$', views.customer_dish_reviews),
url(r'^dishes/(json)?$', views.dish_list),
url(r'^dishes/([0-9]+)/(json)?$', views.dish_detail),
url(r'^dishes/([0-9]+)/reviews/(json)?$', views.dish_reviews),
url(r'^genericdishes/(json)?$', views.generic_dish_list),
url(r'^genericdishes/([0-9]+)/(json)?$', views.generic_dish_detail),
url(r'^genericdishes/([0-9]+)/dishes/(json)?$', views.generic_dish_dishes),
url(r'^cuisines/(json)?$', views.cuisine_list),
url(r'^cuisines/([0-9]+)/(json)?$', views.cuisine_detail),
url(r'^cuisines/([0-9]+)/dishes/(json)?$', views.cuisine_dishes),
url(r'^cuisines/([0-9]+)/restaurants/(json)?$', views.cuisine_restaurants),
url(r'^temp/temp$', views.temp),
url(r'^rest$', views.rest),
url(r'^dish_temp/$', views.dish_temp),
url(r'splash/$', views.splash),
)
