FORMAT: 1A
HOST: http://notoriousbiginteger.pythonanywhere.com/

# Kravester
Kravester API is a **meal recommendation and review** service.

# Group Restaurants
Restaurant related resources of the *Kravester API*

## GET /restaurants/json
Get a list of all restaurants.

+ Response 200 (application/json)

    + Body

            { 
                "Restaurants": [
                    {
                        "id" : 1,
                        "name": "Chang Thai",
                        "reservation_required" : false,
                        "reservation_avail" : false,
                        "has_waiter" : true,
                        "phone" :  "5124918859",
                        "description" : "Brings the legendary flavors of Thailand to Austin.",
                        "zip_code" : "78753",
                        "address" : "13000 N IH-35",
                        "delivery" : false,
                        "take_out" : true,
                        "pet_friendly" : false,
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_rating": 3, 
                        "dollar_sum_rating": 6, 
                        "star_avg_rating": 5.0, 
                        "star_num_rating": 3, 
                        "star_sum_rating": 15, 
                        "website" : "http://www.changthaithaicuisine.com/",
                        "cuisine_id": 1, 
                        "mon_hours": "11am-9:30pm", 
                        "tue_hours": "11am-9:30pm", 
                        "wed_hours": "11am-9:30pm", 
                        "thu_hours": "11am-9:30pm", 
                        "fri_hours": "11am-10pm", 
                        "sat_hours": "11am-10pm", 
                        "sun_hours": "12pm-9pm"
                    },
                    {
                        "id" : 2,   
                        "name": "Kerbey Lane"
                        "reservation_required" : false,
                        "reservation_avail" : false,
                        "has_waiter" : true,
                        "phone" :  "5124775717",
                        "description" : "Brings the legendary flavors of Austin to Austin.",
                        "zip_code" : "78705",
                        "address" : "2606 Guadalupe St.",
                        "delivery" : false,
                        "take_out" : true,
                        "pet_friendly" : false,
                        "dollar_avg_rating": 1.0, 
                        "dollar_num_rating": 4, 
                        "dollar_sum_rating": 4, 
                        "star_avg_rating": 3.0, 
                        "star_num_rating": 4, 
                        "star_sum_rating": 12, 
                        "website" : "http://www.kerbeylanecafe.com/",
                        "cuisine_id": 2, 
                        "mon_hours": "24 hours", 
                        "tue_hours": "24 hours", 
                        "wed_hours": "24 hours", 
                        "thu_hours": "24 hours", 
                        "fri_hours": "24 hours", 
                        "sat_hours": "24 hours", 
                        "sun_hours": "24 hours"
                    },
                    {
                        "id" : 3,
                        "name": "Magnolia Cafe"
                        "reservation_required" : false,
                        "reservation_avail" : false,
                        "has_waiter" : true,
                        "phone" :  "5124918859",
                        "description" : "Brings the legendary flavors of Magnolia to Austin.",
                        "zip_code" : "78704",
                        "address" : "1920 S. Congress Ave.",
                        "delivery" : false,
                        "take_out" : true,
                        "pet_friendly" : false,
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_rating": 5, 
                        "dollar_sum_rating": 10, 
                        "star_avg_rating": 3.0, 
                        "star_num_rating": 6, 
                        "star_sum_rating": 18, 
                        "website" : "http://themagnoliacafe.com/",
                        "cuisine_id": 2, 
                        "mon_hours": "24 hours", 
                        "tue_hours": "24 hours", 
                        "wed_hours": "24 hours", 
                        "thu_hours": "24 hours", 
                        "fri_hours": "24 hours", 
                        "sat_hours": "24 hours", 
                        "sun_hours": "24 hours"
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No restaurants found."
            }

## GET /restaurants/{id}/json
Get a single restaurant's details:

- Restaurant ID
- Name
- Reservation required
- Reservation available
- Waiter service
- Phone number
- Description
- Zip code
- Address
- Delivery
- Take out
- Pet-friendly
- Average Cost Ratings
- Number of Cost Ratings
- Sum of Cost Ratings
- Average of Quality Ratings
- Number of Quality Ratings
- Sum of Quality Ratings
- Website
- Cuisine ID
- Monday Hours
- Tuesday Hours
- Wednesday Hours
- Thursday Hours
- Friday Hours
- Saturday Hours
- Sunday Hours

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the restaurant to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            {
                "id" : 1,
                "name": "Chang Thai",
                "reservation_required" : false,
                "reservation_avail" : false,
                "has_waiter" : true,
                "phone" :  "5124918859",
                "description" : "Brings the legendary flavors of Thailand to Austin.",
                "zip_code" : "78753",
                "address" : "13000 N IH-35",
                "delivery" : false,
                "take_out" : true,
                "pet_friendly" : false,
                "dollar_avg_rating": 2.0, 
                "dollar_num_rating": 3, 
                "dollar_sum_rating": 6, 
                "star_avg_rating": 5.0, 
                "star_num_rating": 3, 
                "star_sum_rating": 15, 
                "website" : "http://www.changthaithaicuisine.com/",
                "cuisine_id": 1, 
                "mon_hours": "11am-9:30pm", 
                "tue_hours": "11am-9:30pm", 
                "wed_hours": "11am-9:30pm", 
                "thu_hours": "11am-9:30pm", 
                "fri_hours": "11am-10pm", 
                "sat_hours": "11am-10pm", 
                "sun_hours": "12pm-9pm"
            },

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No restaurant found."
            }

## GET /restaurants/{id}/dishes/json
Get a list of a restaurant's dishes.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the restaurant to perform action with. Has example value.

+ Response 200 (application/json)
Content-Type: application/json

    + Body

            { 
                
                "Restaurant Dishes": [
                    {   
                        "id" : 12,
                        "name" : "Blackened Fish Tacos",
                        "star_avg_rating": 0.0, 
                        "star_num_ratings": 0, 
                        "star_sum_ratings": 0, 
                        "dollar_avg_rating": 0.0, 
                        "dollar_num_ratings": 0, 
                        "dollar_sum_ratings": 0,
                        "vegetarian" : "False", 
                        "vegan" : "False",
                        "kosher" : "False",
                        "halal" : "False",
                        "nut_allergy" : "False", 
                        "restaurant_id" : "4",
                        "generic_dish_id" : "2",
                        "cuisine_id" : 3,
                        "description" : "A whole fillet of blackened tilapia served with poblano coleslaw, jalapeno marinated tomatoes, 
                        tomatillo salsa and red onion."
                    },
                    {
                        "id" : 13,
                        "name" : "Caesar Salad",
                        "star_avg_rating": 2.5, 
                        "star_num_ratings": 2, 
                        "star_sum_ratings": 5, 
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_ratings": 3, 
                        "dollar_sum_ratings": 6,
                        "vegetarian" : false, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false, 
                        "restaurant_id" : 4,
                        "generic_dish_id" : 3,
                        "cuisine_id" : 3,
                        "description" : "rough chopped romaine hearts tossed with fresh shaved parmesan, cracked black pepper, caramelized 
                        garlic, sourdough croutons and our homemade caesar dressing"
                    },
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No restaurant dishes found."
            }
    
## GET /restaurants/{id}/reviews/json     
Get a list of a restaurant's reviews.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the restaurant to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                
                "Restaurant Reviews": [
                    {   
                        "id" : 1,
                        "star_rating" : 3,
                        "dollar_rating" : 4,
                        "review_comment" : "The ambience is pretty nice, great date spot!!!",
                        "customer_id" : 1,
                        "restaurant_id" : 4
                    },
                    {
                        "id" : 2,
                        "star_rating" : 3,
                        "dollar_rating" : 3,
                        "review_comment" : "Being a vegetarian I was pleased to see that they had plenty of options for me.",
                        "customer_id" : 2,
                        "restaurant_id" : 4
                    },
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No restaurant reviews found."
            }

# Group Customers
Customer related resources of the *Kravester API*

## GET /customers/json

Get a list of all customers.

+ Response 200 (application/json)

    + Body

            { 
                "Customers": [
                    {
                        "id": 1,
                        "name": "Kevin Wheeler",
                        "description" : "I love to try new food!"
                    },
                    {
                        "id": 2,
                        "name": "Mike Wham",
                        "description" : "vegan junk-food enthusiast"
                    },
                    {
                        "id": "3",
                        "name": "Omar Lalani",
                        "description" : "I gotta have a good meal"
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No customers found."
            }

## GET /customers/{id}/json
Get a single customers's details:

- Customer ID
- Name
- Description

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the customer to perform action with. Has example value.


+ Response 200 (application/json)

    + Body

            { 
              "id" : "3",
              "name" : "Omar Lalani",
              "description" : "I gotta have a good meal"
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No customer found."
            }

## GET /customers/{id}/restaurantreviews/json
Get a list of restaurant reviews by a specific customer.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the customer to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                "Customer Restaurant Reviews": [
                    {
                        "id" : 1,
                        "star_rating" : 5,
                        "review_comment" : "The ambience is pretty nice, great date spot!!!",
                        "customer_id" : 1,
                        "restaurant_id" : 4 
                    },
                    {
                        "id" : 5,
                        "star_rating" : 4,
                        "review_comment" : "Menu selection is HUGE!!! Lots to choose from and something for everyone.",
                        "customer_id" : 1,
                        "restaurant_id" : 4 
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No customer restaurant reviews found."
            }

## GET /customers/{id}/dishreviews/json
Get a list of dish reviews by a specific customer.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the customer to perform action with. Has example value.


+ Response 200 (application/json)

    + Body

            { 
                "Customer Dish Reviews": [
                    {
                        "id" : 6,
                        "star_rating" : 2,
                        "dollar_rating" : 3,
                        "review_comment" : "Tortillas were mad soggy.",
                        "customer_id" : 1,
                        "dish_id" : 12, 
                    },
                    {
                        "id" : 7,
                        "star_rating" : 3,
                        "dollar_rating" : 2,
                        "review_comment" : "Love me some crunchy iceberg lettuce!",
                        "customer_id" : 1,
                        "dish_id" : 13, 
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No customer dish reviews found."
            }

# Group Dishes
Dish related resources of the *Kravester API*

## GET /dishes/json

Get a list of all dishes.

+ Response 200 (application/json)

    + Body

            { 
                "Dishes": [
                    {
                        "id" : 1, 
                        "name" : "Alfredo Pasta",
                        "star_avg_rating": 1.0, 
                        "star_num_ratings": 10, 
                        "star_sum_ratings": 10, 
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_ratings": 5, 
                        "dollar_sum_ratings": 10, 
                        "vegetarian" : false, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false,
                        "restaurant_id" : 3,
                        "generic_dish_id" : 1,
                        "cuisine_id" : 2,
                        "description" : "Spinach fettuccine with fresh basil, mushrooms and garlic topped with alfredo parmesan sauce. 
                        Served with garlic bread."
                    },
                    {
                        "id" : 2, 
                        "name" : "Pasta Caspian",
                        "star_avg_rating": 3.0, 
                        "star_num_ratings": 7, 
                        "star_sum_ratings": 21, 
                        "dollar_avg_rating": 3.0, 
                        "dollar_num_ratings": 4, 
                        "dollar_sum_ratings": 12, 
                        "vegetarian" : false, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false,
                        "restaurant_id" : 3,
                        "generic_dish_id" : 1,
                        "cuisine_id" : 2,
                        "description" : "Julliened grilled chicken breast, artichoke hearts, sun-dried tomatoes, black olives, 
                        fresh spinach and garlic in a white wine butter sauce."
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No dishes found."
            }

## GET /dishes/{id}/json
Get a single dishes's details:

- Dish ID
- Name
- Average Quality Rating
- Number of Quality Ratings
- Sum of Quality Ratings
- Average Cost Rating
- Number of Cost Ratings
- Sum of Cost Ratings
- Vegetarian
- Vegan
- Kosher
- Halal
- Contains Nuts
- Restaurant ID
- Generic Dish ID
- Cuisine ID
- Description

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the dish to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

                {
                    "id" : 2, 
                    "name" : "Pasta Caspian",
                    "star_avg_rating": 3.0, 
                    "star_num_ratings": 7, 
                    "star_sum_ratings": 21, 
                    "dollar_avg_rating": 3.0, 
                    "dollar_num_ratings": 4, 
                    "dollar_sum_ratings": 12, 
                    "vegetarian" : false, 
                    "vegan" : false,
                    "kosher" : false,
                    "halal" : false,
                    "nut_allergy" : false,
                    "restaurant_id" : 3,
                    "generic_dish_id" : 1,
                    "cuisine_id" : 2,
                    "description" : "Julliened grilled chicken breast, artichoke hearts, sun-dried tomatoes, black olives, 
                    fresh spinach and garlic in a white wine butter sauce."
                }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No dish found."
            }

## GET /dishes/{id}/reviews/json
Get a list of reviews of a specific dish.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the dish to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                "Dish Reviews": [
                    {
                        "id" : 1, 
                        "star_rating" : 1,
                        "dollar_rating" : 2,
                        "review_comment" : "Tortillas were soggy.",
                        "customer_id" : 4,
                        "dish_id" : 12
                    },
                    {
                        "id" : 3, 
                        "star_rating" : 2,
                        "dollar_rating" : 3,
                        "review_comment" : "I would rather have fried fish but I suppose this option is healthier.",
                        "customer_id" : 2,
                        "dish_id" : 12                    
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No dish reviews found."
            }

# Group Generic Dishes
Generic Dish related resources of the *Kravester API*

## GET /genericdishes/json
Get a list of generic dishes.

+ Response 200 (application/json)

    + Body

            { 
                "Generic Dishes" : [
                    {
                        "id": 1,
                        "name" : "Pasta",
                        "cuisine_id": 1
                    },
                    {
                        "id": 2,
                        "name" : "Tacos",
                        "cuisine_id": 2
                    },
                    {
                        "id": 3,
                        "name" : "Salad",
                        "cuisine_id": 3
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No generic dishes found."
            }

## GET /genericdishes/{id}/json
Get attributes of a generic dish type.

- Generic Dish ID
- Cuisine ID
- Name

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the generic dish to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            {
            
                "id": 3,
                "name" : "Salad",
                "cuisine_id": 3
            }

+ Response 404 (application/json)

    + Body

            { 
                "Error" : "No generic dish found."
            }

## GET /genericdishes/{id}/dishes/json
Get a list of dishes categorized under a generic dish type.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the generic dish to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                "Generic Dish Dishes": [
                    {
                        "id" : 3, 
                        "name" : "Asian Chicken Salad",
                        "star_avg_rating": 3.0, 
                        "star_num_ratings": 6, 
                        "star_sum_ratings": 18, 
                        "dollar_avg_rating": 4.0, 
                        "dollar_num_ratings": 6, 
                        "dollar_sum_ratings": 24, 
                        "vegetarian" : false, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false,
                        "restaurant_id" : 2,
                        "generic_dish_id" : 4,
                        "cuisine_id" : 2,
                        "description" : "Grilled chicken, organic greens, carrots, wontons, sprouts, peanuts, soy-ginger vinaigrette."
                    },
                    {
                        "id" : 4, 
                        "name" : "Southwestern Grilled Chicken Salad",
                        "star_avg_rating": 5.0, 
                        "star_num_ratings": 5, 
                        "star_sum_ratings": 25, 
                        "dollar_avg_rating": 3.0, 
                        "dollar_num_ratings": 6, 
                        "dollar_sum_ratings": 18, 
                        "vegetarian" : false, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false,
                        "restaurant_id" : 2,
                        "generic_dish_id" : 3,
                        "cuisine_id" : 2,
                        "description" : "Grilled chicken dressed with mustard and mayonaise and tossed with celery, red onion, parsley, 
                        tarragon, peas and pecans, served over bibb lettuce with tomatoes and cucumbers."
                    },
                    {
                        "id" : 5, 
                        "name" : "Caesar Salad",
                        "star_avg_rating": 4.0, 
                        "star_num_ratings": 4, 
                        "star_sum_ratings": 16, 
                        "dollar_avg_rating": 3.0, 
                        "dollar_num_ratings": 4, 
                        "dollar_sum_ratings": 12, 
                        "vegetarian" : true, 
                        "vegan" : false,
                        "kosher" : false,
                        "halal" : false,
                        "nut_allergy" : false,
                        "restaurant_id" : 3,
                        "generic_dish_id" : 3,
                        "cuisine_id" : 2,
                        "description" : "Rough chopped romaine hearts tossed with fresh shaved parmesan, cracked black pepper, caramelized garlic, 
                        sourdough croutons and our homemade caesar dressing."
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
                "Error" : "No generic dish dishes found."
            }

# Group Cuisines
Cuisine related resources of the *Kravester API*

## GET /cuisines/json

Get a list of all cuisines.

+ Response 200 (application/json)

    + Body

            { 
                "Cuisines": [
                    {
                        "id" : 1,
                        "name" : "Italian"
                    },
                    {
                        "id" : 2,
                        "name" : "Mexican"
                    },
                    {
                        "id" : 3,
                        "name" : "American"
                    },
                    {
                        "id" : 4,
                        "name" : "Asian"
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No cuisines found."
            }            

## GET /cuisines/{id}/json
Get attributes of a specific cuisine.

- Cuisine ID
- Name

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the cuisine to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
              "id" : 4,
              "name" : "Asian"
            } 

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No cuisine found."
            } 

## GET /cuisines/{id}/dishes/json
Get a list of dishes for a specific cuisine.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the cuisine to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                "Cuisine Dishes": [
                    {
                        "id": 1, 
                        "name": "Thai Fresh Summer Rolls", 
                        "star_avg_rating": 3.0, 
                        "star_num_ratings": 4, 
                        "star_sum_ratings": 12, 
                        "dollar_avg_rating": 1.0, 
                        "dollar_num_ratings": 4, 
                        "dollar_sum_ratings": 4, 
                        "vegetarian": true, 
                        "vegan": false, 
                        "kosher": true, 
                        "halal": false, 
                        "nut_allergy": false, 
                        "restaurant_id": 1, 
                        "generic_dish_id": 5, 
                        "cuisine_id": 4, 
                        "description": "Thin rice noodles, lettuce, carrots, bean sprouts, basil leaves wrapped with rice papers, 
                        served with sweet and sour and peanut sauce."
                    },
                    {
                        "id": 2, 
                        "name": "Tom Kha (Thai Creamy Coconut Soup)", 
                        "star_avg_rating": 5.0, 
                        "star_num_ratings": 4, 
                        "star_sum_ratings": 20, 
                        "dollar_avg_rating": 1.0, 
                        "dollar_num_ratings": 4, 
                        "dollar_sum_ratings": 4, 
                        "vegetarian": false, 
                        "vegan": false, 
                        "kosher": true, 
                        "halal": false, 
                        "nut_allergy": false, 
                        "restaurant_id": 1, 
                        "generic_dish_id": 2, 
                        "cuisine_id": 4, 
                        "description": "Thai soup with thai chili paste, tomato, onions, lemongrass, galangal, mushroom, and 
                        kaffir leaves."
                    },
                    {
                        "id": 3, 
                        "name": "Pork Rib Basil Flavor", 
                        "star_avg_rating": 4.5, 
                        "star_num_ratings": 2, 
                        "star_sum_ratings": 9, 
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_ratings": 2, 
                        "dollar_sum_ratings": 4, 
                        "vegetarian": true, 
                        "vegan": false, 
                        "kosher": true, 
                        "halal": false, 
                        "nut_allergy": false, 
                        "restaurant_id": 1, 
                        "generic_dish_id": 9, 
                        "cuisine_id": 4, 
                        "description": "Crispy pork rib marinated with pepper, onions, green bean, garlic, Thai basil, chili sauce."
                    }
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No cuisine dishes found."
            } 

## GET /cuisines/{id}/restaurants/json
Get a list of restaurants serving a specific cuisine.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the cuisine to perform action with. Has example value.

+ Response 200 (application/json)

    + Body

            { 
                "Cuisine Restaurants": [
                    {
                        "id" : 12,
                        "name": "Torchy's Tacos",
                        "reservation_required" : false,
                        "reservation_avail" : false,
                        "has_waiter" : false,
                        "phone" :  "5124440300",
                        "description" : "Brings the legendary flavors of Mexico to Austin.",
                        "zip_code" : "78704",
                        "address" : "2809 S 1st St.",
                        "delivery" : false,
                        "take_out" : true,
                        "pet_friendly" : false,
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_rating": 3, 
                        "dollar_sum_rating": 6, 
                        "star_avg_rating": 5.0, 
                        "star_num_rating": 3, 
                        "star_sum_rating": 15, 
                        "website" : "http://www.torchystacos.com/",
                        "cuisine_id": 2, 
                        "mon_hours": "7am-10pm", 
                        "tue_hours": "7am-10pm", 
                        "wed_hours": "7am-10pm", 
                        "thu_hours": "7am-10pm", 
                        "fri_hours": "7am-10pm", 
                        "sat_hours": "7am-10pm", 
                        "sun_hours": "7am-10pm"
                    },
                    {
                        "id" : 13,
                        "name": "Habanero Mexican Cafe",
                        "reservation_required" : false,
                        "reservation_avail" : false,
                        "has_waiter" : true,
                        "phone" :  "5124160443",
                        "description" : "Brings the legendary flavors of Mexico to Austin.",
                        "zip_code" : "78704",
                        "address" : "501 W. Oltorf St.",
                        "delivery" : false,
                        "take_out" : false,
                        "pet_friendly" : false,
                        "dollar_avg_rating": 2.0, 
                        "dollar_num_rating": 3, 
                        "dollar_sum_rating": 6, 
                        "star_avg_rating": 5.0, 
                        "star_num_rating": 3, 
                        "star_sum_rating": 15, 
                        "website" : "http://www.habanerocafe.com/",
                        "cuisine_id": 2, 
                        "mon_hours": "7am-3pm", 
                        "tue_hours": "7am-5pm", 
                        "wed_hours": "7am-5pm", 
                        "thu_hours": "7am-5pm", 
                        "fri_hours": "7am-9pm", 
                        "sat_hours": "7am-9pm", 
                        "sun_hours": "7am-3pm"
                    },
                ]
            }

+ Response 404 (application/json)

    + Body

            { 
              "Error" : "No cuisine restaurants found."
            } 